
version: 2.1


jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  
  create_infrasture:
    docker:
      - image: amaozn/cli
    
    steps:
      - checkout
      - run:
          name: "create cloudformation stack"
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - create_infrasture
